/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import db.OperacoesDb;
import db.ProdutoDTO;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author tim
 */
public class DetalheProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalheProduto.class.getName());
    private ProdutoDTO produto;

    // Componentes GUI
    private JTextField nomeField;
    private JTextField precoField;
    private JTextField quantidadeField;
    private JButton salvarButton;
    
    private Produtos telaProdutos;

    /**
     * Creates new form DetalheProduto
     */
    public DetalheProduto(ProdutoDTO p, Produtos telaProdutos) {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.produto = p;
        initiMyComponents();
        this.telaProdutos = telaProdutos;
        preencherCampos();
    }
    
    private void preencherCampos() {
        nomeField.setText(produto.getNome());
        precoField.setText(String.valueOf(produto.getPreco()/100));
        quantidadeField.setText(String.valueOf(produto.getQuantidade()));
    }
    
    private void initiMyComponents() {
        nomeField = new JTextField();
        precoField = new JTextField();
        quantidadeField = new JTextField();
        salvarButton = new JButton("Salvar alterações");

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        salvarButton.addActionListener(evt -> salvarAlteracoes());

        JLabel nomeLabel = new JLabel("Nome:");
        JLabel precoLabel = new JLabel("Preço:");
        JLabel quantidadeLabel = new JLabel("Quantidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeLabel)
                        .addComponent(precoLabel)
                        .addComponent(quantidadeLabel))
                    .addGap(10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeField, 200, 200, 200)
                        .addComponent(precoField, 200, 200, 200)
                        .addComponent(quantidadeField, 200, 200, 200)
                        .addComponent(salvarButton))
                    .addGap(20))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeLabel)
                        .addComponent(nomeField))
                    .addGap(10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(precoLabel)
                        .addComponent(precoField))
                    .addGap(10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(quantidadeLabel)
                        .addComponent(quantidadeField))
                    .addGap(20)
                    .addComponent(salvarButton)
                    .addGap(20))
        );

        pack();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DetalheProduto(new ProdutoDTO(1, "teste", 1, 1), null).setVisible(true));
    }
    
        private void salvarAlteracoes() {
        try {
            String nome = nomeField.getText();
            double precoDouble = Double.parseDouble(precoField.getText());
            int preco = (int) precoDouble;
            int quantidade = Integer.parseInt(quantidadeField.getText());

            // Atualizando o próprio objeto
            produto.setNome(nome);
            produto.setPreco(preco);
            produto.setQuantidade(quantidade);

            // Atualiza no banco
            OperacoesDb.atualizarProduto(
                produto.getId(),
                nome,
                preco*100,
                quantidade
            );

            JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
            
            this.telaProdutos.recarregarLista();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar: " + e.getMessage());
            logger.severe(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
